-- LISTA AS PERMISSÕES DO USUÁRIO ATUAL
SHOW GRANTS FOR CURRENT_USER;

-- CRIA UM NOVO USUÁRIO
CREATE USER 'vinicius'@'localhost'  IDENTIFIED BY '123';

-- ATRIBUIR PERMISSÕES PARA O USUÁRIO
GRANT SELECT ON vinicius.* TO 'vinicius'@'localhost';
