SQL = STRUCTURED QUERY LANGUAGE - linguagem de consulta estrutura

CREATE - cria alguma coisa
ALTER - altera alguma coisa
DROP - deleta alguma coisa

na modelagem usamos 
CREATE TABLE - cria uma tabela
ALTER TABLE - altera uma tabela
DROP TABLE - deleta uma tabela

TIPOS DE RESTRIÇÃO NO FOREIGN KEY

NO ACTION - SEM EFEITO IMEDIATO E PODE GERAR ERRO NO BANCO DE DADOS CASO A ESTRTURUA
ESTEJA FEITA PARA A RESTRIÇÃO DE INTEGRIDADE DE DADOS

CASCADE - SE O REGISTRO DA TABELA REFERENCIADA FOR DELETADO, OS REGISTROS DEPENDENTES
TAMBÉM SERÃO AUTOMATICAMENTE DELETADOS

SET NULL - SE O REGISTRO DA TABELA REFERENCIADA FOR DELETADO, OS REGISTROS DEPENDENTES
TERÃO O CAMPO DE CHAVE ESTRANHEIRA MARCADOS COMO NULL (NAO FUNCIOONA EM CAMPOS COM MARCAÇÃO
NOT NULL )

RESTRICT - IMPEDE A EXCLUSÃO DE REGISTROS DA TABELA REFERENCIADA SE HOUVER REGISTROS
DEPENDENTES

COMANDOS BÁSICOS (INSTRUÇÕES) DE SQL

DIVIDIMOS AS INSTRUÇÕES EM ALGUMAS CATEGORIAS, SÃO ELAS:
DDL, DML, DQL, DCL E TCL

DDL -> DATA DEFINITION LANGUAGE (LINGAUGEM DE DEFINIÇÃO DE DADOS)
    CONTÉM COMANDOS UTILIZADOS PARA CRIAR, MODIFICAR OU EXCLUIT ESTRUTURAS DE BANCO DE 
    DADOS. ESTES COMANDOS NÃO MANIPULAM DADOS, APENAS A ESTRUTURA
COMANDOS RELACIONADOS: CREATE, ALTER, DROP, TRUNCATE
EXEMPLOS: 
CREATE TABLE nome_tabela
ALTER TABLE nome_tabela
DROP TABLE nome_tabela
TRUNCATE TABLE nome_tabela

-----------------------------------------

DML -> DATA MANIPULATION LANGUAGE (LINGAGUEM DE MANIPULAÇÃO DE DADOS)
    CONTÉM COMANDOS UTILIZADOS PARA MANIPULAR DADOS NAS TABELAS INCLUINDO INSERÇÃO,
    ATUALIZAÇÃO E REMOÇÃO DE REGISTROS. 
    COMANDOS RELACIONADOS: INSERT, UPDATE, DELETE 
    EXEMPLOS:
    INSERT INTO nome_tabela 
    UPDATE nome_tabela
    DELETE from nome_tabela

-----------------------------------------

DQL -> DATA QUERY LANGUAGE (LINGUAGEM DE CONSULTA DE DADOS)
    CONTÉM UM COMANDO UTILIZADO PARA CONSULTAR OS DADOS NO VANCO DE DADOSOU SEJA,
    PARA FAZER QUERIES (CONSULTAS) 
    COMANDOS RELACIONADOS: SELECT

    EXEMPLO : SELECT * FROM nome_tabela ( * = TODAS AS COLUNAS DE UMA TABELA. É POSSIVEL TAMBÉM INFROMAR O NOME DE COLUNAS
    SEPARANDO-AS POR VÍRGULA)

-----------------------------------------

DCL -> DATA CONTROL LANGUAGE (LINGUAGEM DE CONTROLE DE DADOS)
    CONTÉM COMANDOS QUE CONTROLAM O ACESSO E PERMISSÕES DE USUÁRIOS SOBRE OBJETOS DE 
    BANCO DE DADOS COMO TABELAS, VIEWS E ETC.
    COMANDOS RELACIONADOS: GRANT, REVOKE 
    EXEMPLOS:
    GRANT SELECT, INSERT ON nome_tabela
    REVOKE INSERT ON nome_tabela

-----------------------------------------

TCL -> TRANSCRITION CONTROL LANGUAGE (LINUGUGAEM DE CONTROLE DE TRANSAÇÕES)
    CONTÉM COMANDOS QUE GERENCIAM AS TRANSAÇÕES DE BANCO DE DADOS. TRANSAÇÕES SÃO BLOCOS
    DE OPERAÇÕES QUE DEVEM SER EXECUTADAS JUNTAS OU NÃO EXECUTADAS.
    COMANDOS RELACIONADOS: BEGIN/START TRANSACTION, COMMIT, ROLLBACK, SABEPOINT

    EXEMPLOS:
    START TRANSACTION nome_transacao
        INSERT INTO ... 
    COMMIT; --SE CASO FOI TUDO CERTO

    START TRANSACTION
        UPDATE ...
    ROLLBACK; --SE ALGO DER ERRADO

    RELEASE SAVEPOINT nome_transacao