SQL = STRUCTURED QUERY LANGUAGE - linguagem de consulta estrutura

CREATE - cria alguma coisa
ALTER - altera alguma coisa
DROP - deleta alguma coisa

na modelagem usamos 
CREATE TABLE - cria uma tabela
ALTER TABLE - altera uma tabela
DROP TABLE - deleta uma tabela

TIPOS DE RESTRIÇÃO NO FOREIGN KEY

NO ACTION - SEM EFEITO IMEDIATO E PODE GERAR ERRO NO BANCO DE DADOS CASO A ESTRTURUA
ESTEJA FEITA PARA A RESTRIÇÃO DE INTEGRIDADE DE DADOS

CASCADE - SE O REGISTRO DA TABELA REFERENCIADA FOR DELETADO, OS REGISTROS DEPENDENTES
TAMBÉM SERÃO AUTOMATICAMENTE DELETADOS

SET NULL - SE O REGISTRO DA TABELA REFERENCIADA FOR DELETADO, OS REGISTROS DEPENDENTES
TERÃO O CAMPO DE CHAVE ESTRANHEIRA MARCADOS COMO NULL (NAO FUNCIOONA EM CAMPOS COM MARCAÇÃO
NOT NULL )

RESTRICT - IMPEDE A EXCLUSÃO DE REGISTROS DA TABELA REFERENCIADA SE HOUVER REGISTROS
DEPENDENTES

